services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - typescript_template_postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - typescript_template_mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

volumes:
  typescript_template_postgres-data:
  typescript_template_mongodb-data:
